### PR TITLE
Master PIG script

### PR DESCRIPTION
**Pull request by mmeoni**
PIG script producing all equivalent Oracle views in one go

### CODE REVIEW

**Comment by nikmagini** [comment]
Ciao Marco,

please let me know if/when you really want to merge this commit :)

Cheers
N.

**Comment by mmeoni** [comment]
title too funny??
.m

**Comment by nikmagini** [comment]
Seriously: since you closed the pull request, I have to assume that you don't want me to merge anymore.
I suppose it was just a mistake, so If you want me to merge, please reopen it.

**Comment by mmeoni** [comment]
done

**Pull request merged**
